# recent version of docker-compose
version: "3.8"

services:
  # my application name is app-dev
  chat-app:
    build:
      # context is the path to the Dockerfile where i want to run the docker-compose
      context: .
      # dockerfile is the name of the dockerfile which i created in the root directory of the project
      dockerfile: Dockerfile
    # ports is the port number where i want to run my application locally:container-port
    ports:
      - "3001:3001"
    # volumes is the path to the project directory where i want to run the docker-compose
    # it stores the data in the container and syncs it with the project container data when we sotp or start the container. localdireatory:containerdirectory
    volumes:
      - .:/app
      # this is to ignore the node_modules directory in the project directory because it is too large to store in the container which will slow down the container
      - /app/node_modules
  proxy-server:
    build:
      context: .
      dockerfile: Dockerfile
    command: "node proxy.js"
    ports:
      - "3002:3002"
    volumes:
      - .:/app
      - /app/node_modules